MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: ./source_ap494ap50729.pth
  BACKBONE:
    CONV_BODY: "R-101-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  FCOS:
    NUM_CLASSES: 2
    # Something for generating the pseudo label
    # PRE_NMS_TOP_N: 10
DATASETS:
  TRAIN: ("wce_train_swstyle",)
  TEST: ("wce_test_cocostyle",)
INPUT:
  MIN_SIZE_TRAIN: (384, 400, 426, 468, 500, 512)
SOLVER:
  BASE_LR: 0.0001
  STEPS: (50000,)
  MAX_ITER: 20000
  WARMUP_ITERS: 0
  SFDA_ON: True
  ##################
  SFDA_STAGE: 5
  ##################
OUTPUT_DIR:
  "outputs/smpt_wce"